services:
  redis:
    build:
      context: './redis'
      dockerfile: 'Dockerfile'
      args:
        REDIS_VERSION: ${REDIS_VERSION}
        REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - '${DATA_PATH_HOST}:/data'
    ports:
      - '${REDIS_PORT}:6379'
